name: Zeiterfassung
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

# Add developer dependencies here.
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1